name: Main
on: [push, pull_request]
jobs:
    test:
        name: 'Node.js v${{ matrix.node }}.x, ${{ matrix.os }}'
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node: [10, 12]
                os: [ubuntu-latest, windows-latest, macos-latest]

        steps:
            - uses: actions/checkout@master

            - name: 'use ${{ matrix.node }}'
              uses: actions/setup-node@master
              with:
                  version: ${{ matrix.node }}

            - name: 'yarn install'
              run: |
                  npm install -g yarn
                  yarn add codecov -g
                  yarn install

            - name: yarn build
              run: yarn build
# env: CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
# if: success && ${{ matrix.node_version }} == '10' && ${{ matrix.os }} == 'ubuntu-latest'
# - run: codecov -f coverage/*.json
